CREATE TABLE "feedback" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"verification_id" integer,
	"user_id" varchar,
	"rating" integer NOT NULL,
	"comment" text,
	"helpful" boolean,
	"accuracy" varchar,
	"suggested_result" varchar,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ip_verifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ip_verifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ip_address" varchar NOT NULL,
	"last_verification_date" timestamp NOT NULL,
	"verification_count" integer DEFAULT 1,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "ip_verifications_ip_address_unique" UNIQUE("ip_address")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" varchar PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trusted_patterns" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trusted_patterns_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"filename" varchar NOT NULL,
	"metadata" jsonb NOT NULL,
	"patterns" jsonb NOT NULL,
	"uploaded_at" timestamp DEFAULT now(),
	"status" varchar DEFAULT 'active'
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY NOT NULL,
	"email" varchar,
	"phone" varchar,
	"first_name" varchar,
	"last_name" varchar,
	"profile_image_url" varchar,
	"google_id" varchar,
	"auth_provider" varchar NOT NULL,
	"verification_code" varchar,
	"code_expiry" timestamp,
	"is_verified" boolean DEFAULT false,
	"role" varchar DEFAULT 'user',
	"subscription_status" varchar DEFAULT 'free',
	"stripe_customer_id" varchar,
	"stripe_subscription_id" varchar,
	"daily_verifications_used" integer DEFAULT 0,
	"last_verification_date" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_phone_unique" UNIQUE("phone"),
	CONSTRAINT "users_google_id_unique" UNIQUE("google_id")
);
--> statement-breakpoint
CREATE TABLE "verification_results" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "verification_results_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar,
	"filename" varchar NOT NULL,
	"result" varchar NOT NULL,
	"confidence" integer NOT NULL,
	"metadata" jsonb NOT NULL,
	"analysis_details" jsonb NOT NULL,
	"ip_address" varchar,
	"verified_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_verification_id_verification_results_id_fk" FOREIGN KEY ("verification_id") REFERENCES "public"."verification_results"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "verification_results" ADD CONSTRAINT "verification_results_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IDX_session_expire" ON "sessions" USING btree ("expire");