-- Audit log for the notification engine (Part 5).
-- Tracks per-event-type filtered sends, skips, queued deferrals, and failures.
-- Kept separate from notification_log to decouple from the legacy dispatcher schema.
CREATE TABLE IF NOT EXISTS "notif_engine_log" (
  "id"                   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"              varchar NOT NULL REFERENCES "users"("id"),
  "change_id"            integer NOT NULL REFERENCES "sponsor_changes"("id"),
  "event_type"           varchar NOT NULL,
  "channel"              varchar NOT NULL DEFAULT 'email',
  "status"               varchar NOT NULL,
  "sent_at"              timestamp,
  "deliver_after"        timestamp,
  "provider_message_id"  varchar,
  "error_details"        text,
  "created_at"           timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_notif_engine_log_user_id"       ON "notif_engine_log"("user_id");
CREATE INDEX IF NOT EXISTS "idx_notif_engine_log_change_id"     ON "notif_engine_log"("change_id");
CREATE INDEX IF NOT EXISTS "idx_notif_engine_log_status"        ON "notif_engine_log"("status");
CREATE INDEX IF NOT EXISTS "idx_notif_engine_log_deliver_after" ON "notif_engine_log"("deliver_after");
