-- ============================================================
-- Migration 0022: Push notification subscriptions
--
-- Context: Phase 2 of notification engine upgrade adds browser
-- push notifications via Web Push API (VAPID). Each user may
-- subscribe from multiple devices; each device gets one row.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id       VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint      TEXT NOT NULL,
  p256dh        VARCHAR NOT NULL,
  auth          VARCHAR NOT NULL,
  device_name   VARCHAR,
  user_agent    TEXT,
  created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP NOT NULL DEFAULT NOW(),

  -- Prevent duplicate subscriptions from the same device
  CONSTRAINT uq_push_subscriptions UNIQUE (user_id, endpoint)
);

-- Speed up lookups by user for sending notifications
CREATE INDEX idx_push_subscriptions_user_id ON push_subscriptions(user_id);

COMMIT;
