CREATE TABLE "ai_generation_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_generation_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"snapshot_date" date NOT NULL,
	"headline_generated" text,
	"validation_passed" boolean NOT NULL,
	"model_used" text NOT NULL,
	"error_details" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "company_watches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_watches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"organisation_name" varchar NOT NULL,
	"organisation_name_normalized" varchar NOT NULL,
	"town_city" varchar,
	"fingerprint" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "csv_archive" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "csv_archive_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"snapshot_date" date NOT NULL,
	"file_path" text NOT NULL,
	"record_count" integer NOT NULL,
	"checksum_sha256" text NOT NULL,
	"source_url" text,
	"is_valid" boolean DEFAULT true NOT NULL,
	"downloaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'SYNCED' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "daily_digest" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daily_digest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"snapshot_date" date NOT NULL,
	"added_count" integer NOT NULL,
	"updated_count" integer NOT NULL,
	"removed_count" integer NOT NULL,
	"headline_generated" text NOT NULL,
	"headline_variants" jsonb NOT NULL,
	"generated_at" timestamp DEFAULT now(),
	"displayed_on_landing" boolean DEFAULT false,
	"selected_variant_index" integer DEFAULT 0,
	"ai_model" text DEFAULT 'deepseek-chat',
	CONSTRAINT "daily_digest_snapshot_date_unique" UNIQUE("snapshot_date")
);
--> statement-breakpoint
CREATE TABLE "diff_results" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "diff_results_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_date" date NOT NULL,
	"added_count" integer DEFAULT 0 NOT NULL,
	"removed_count" integer DEFAULT 0 NOT NULL,
	"attribute_change_count" integer DEFAULT 0 NOT NULL,
	"diff_duration_ms" integer,
	"diff_json_path" text,
	"diff_json" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "enrichment_queue" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "enrichment_queue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fingerprint" varchar(500) NOT NULL,
	"job_type" varchar(50) NOT NULL,
	"status" varchar(30) DEFAULT 'pending' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"last_attempted_at" timestamp with time zone,
	"next_attempt_at" timestamp with time zone DEFAULT now(),
	"locked_at" timestamp with time zone,
	"locked_by" varchar(255),
	"error_message" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "expert_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "expert_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"file_url" varchar NOT NULL,
	"filename" varchar,
	"status" varchar DEFAULT 'pending',
	"expert_comments" text,
	"expert_verdict" varchar,
	"stripe_session_id" varchar,
	"priority" boolean DEFAULT true,
	"deadline" timestamp,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "global_ai_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "global_ai_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category" varchar NOT NULL,
	"rule_text" text NOT NULL,
	"priority" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "incident_tickets" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "incident_tickets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_name" varchar NOT NULL,
	"severity" varchar NOT NULL,
	"status" varchar DEFAULT 'open' NOT NULL,
	"title" text NOT NULL,
	"context" jsonb NOT NULL,
	"remediation_correlation_id" varchar,
	"resolved_by" varchar,
	"resolved_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ingestion_jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ingestion_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"snapshot_id" text NOT NULL,
	"locked_at" timestamp with time zone,
	"status" text DEFAULT 'pending' NOT NULL,
	CONSTRAINT "ingestion_jobs_snapshot_id_unique" UNIQUE("snapshot_id")
);
--> statement-breakpoint
CREATE TABLE "job_alert_preferences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "job_alert_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"fingerprint" varchar(500) NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "job_listings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "job_listings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fingerprint" varchar(500) NOT NULL,
	"title" varchar(500) NOT NULL,
	"location" varchar(300),
	"salary" varchar(200),
	"source_board" varchar(50) NOT NULL,
	"source_url" text NOT NULL,
	"content_hash" varchar(64) NOT NULL,
	"first_seen" timestamp DEFAULT now(),
	"last_seen" timestamp DEFAULT now(),
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "job_listings_content_hash_unique" UNIQUE("content_hash")
);
--> statement-breakpoint
CREATE TABLE "job_locks" (
	"job_name" varchar(100) PRIMARY KEY NOT NULL,
	"locked_at" timestamp with time zone NOT NULL,
	"locked_by" varchar(255) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "job_trigger_audit" (
	"trigger_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"correlation_id" varchar(64) NOT NULL,
	"job_name" varchar(100) NOT NULL,
	"idempotency_key" varchar(100) NOT NULL,
	"triggered_by" varchar(255) NOT NULL,
	"trigger_source" varchar(20) DEFAULT 'manual' NOT NULL,
	"callback_url" text,
	"callback_status" varchar(20),
	"callback_attempts" integer DEFAULT 0 NOT NULL,
	"callback_last_error" text,
	"callback_last_attempt_at" timestamp,
	"reason" text,
	"status" varchar(20) DEFAULT 'accepted' NOT NULL,
	"failure_reason" text,
	"triggered_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"duration_ms" integer
);
--> statement-breakpoint
CREATE TABLE "monitor_job_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monitor_job_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_date" date NOT NULL,
	"source" varchar NOT NULL,
	"status" varchar NOT NULL,
	"records_processed" integer DEFAULT 0,
	"changes_detected" integer DEFAULT 0,
	"change_summary" jsonb,
	"notifications_sent" integer DEFAULT 0,
	"notifications_skipped" integer DEFAULT 0,
	"notifications_failed" integer DEFAULT 0,
	"notifications_queued" integer DEFAULT 0,
	"duration_ms" integer,
	"error_message" text,
	"is_gap_day" boolean DEFAULT false,
	"started_at" timestamp DEFAULT now(),
	"completed_at" timestamp,
	CONSTRAINT "monitor_job_runs_run_date_unique" UNIQUE("run_date")
);
--> statement-breakpoint
CREATE TABLE "notif_engine_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notif_engine_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"change_id" integer NOT NULL,
	"event_type" varchar NOT NULL,
	"channel" varchar DEFAULT 'email' NOT NULL,
	"status" varchar NOT NULL,
	"sent_at" timestamp,
	"deliver_after" timestamp,
	"provider_message_id" varchar,
	"error_details" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "notif_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"change_id" integer,
	"event_type" varchar NOT NULL,
	"channel" varchar DEFAULT 'email' NOT NULL,
	"company_name" text NOT NULL,
	"success" boolean NOT NULL,
	"provider_message_id" varchar,
	"error_details" text,
	"sent_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "notification_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"change_id" integer NOT NULL,
	"channel" varchar NOT NULL,
	"status" varchar DEFAULT 'queued' NOT NULL,
	"sent_at" timestamp,
	"deliver_after" timestamp,
	"provider_message_id" varchar,
	"error_details" text
);
--> statement-breakpoint
CREATE TABLE "notification_preferences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"email_enabled" boolean DEFAULT true,
	"email" varchar,
	"whatsapp_enabled" boolean DEFAULT false,
	"whatsapp_number" varchar,
	"whatsapp_verified" boolean DEFAULT false,
	"sms_enabled" boolean DEFAULT false,
	"sms_number" varchar,
	"sms_verified" boolean DEFAULT false,
	"webhook_enabled" boolean DEFAULT false,
	"webhook_url" varchar,
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "notification_preferences_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "paid_submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "paid_submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar,
	"email" varchar NOT NULL,
	"package_type" varchar NOT NULL,
	"payment_status" varchar DEFAULT 'pending',
	"stripe_payment_intent_id" varchar,
	"stripe_session_id" varchar,
	"how_applied" text,
	"emails_received" text,
	"confirmation_details" text,
	"employer_name" varchar,
	"job_title" varchar,
	"cos_reference_number" varchar,
	"additional_notes" text,
	"cos_document_path" varchar,
	"supporting_documents_path" jsonb,
	"review_status" varchar DEFAULT 'pending',
	"assigned_to" varchar,
	"priority" boolean DEFAULT false,
	"phone_consultation_requested" boolean DEFAULT false,
	"phone_consultation_scheduled" timestamp,
	"expert_verdict" varchar,
	"expert_confidence" integer,
	"employer_verification_result" jsonb,
	"document_analysis_report" text,
	"alterations_detected" jsonb,
	"recommendations" text,
	"report_delivered" boolean DEFAULT false,
	"report_delivered_at" timestamp,
	"report_path" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "processed_checkouts" (
	"session_id" varchar PRIMARY KEY NOT NULL,
	"processed_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "push_subscriptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "push_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"endpoint" text NOT NULL,
	"p256dh" varchar NOT NULL,
	"auth" varchar NOT NULL,
	"device_name" varchar,
	"user_agent" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "shadow_parity_reports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadow_parity_reports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shadow_run_id" integer NOT NULL,
	"production_correlation_id" varchar(64),
	"job_name" varchar(100) NOT NULL,
	"parity_score" numeric(5, 4) NOT NULL,
	"outcome_match" boolean NOT NULL,
	"duration_drift_ms" integer,
	"records_drift" integer,
	"change_drift_json" jsonb DEFAULT '{}'::jsonb,
	"drift_summary" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shadow_run_results" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadow_run_results_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"correlation_id" varchar(64) NOT NULL,
	"job_name" varchar(100) NOT NULL,
	"run_mode" varchar(20) DEFAULT 'shadow' NOT NULL,
	"trigger_source" varchar(20) DEFAULT 'manual' NOT NULL,
	"triggered_by" varchar(255) NOT NULL,
	"snapshot_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"result" varchar(20) NOT NULL,
	"failure_reason" text,
	"duration_ms" integer,
	"started_at" timestamp NOT NULL,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sponsor_canonical" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sponsor_canonical_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fingerprint" text NOT NULL,
	"current_name" text NOT NULL,
	"town_city" text,
	"county" text,
	"type_rating" text,
	"route" text,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"first_seen" date NOT NULL,
	"last_seen" date NOT NULL,
	"granted_at" date NOT NULL,
	"removed_at" timestamp with time zone,
	"consecutive_misses" integer DEFAULT 0 NOT NULL,
	"historical_names" text[] DEFAULT '{}'
);
--> statement-breakpoint
CREATE TABLE "sponsor_changes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sponsor_changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organisation_name" varchar NOT NULL,
	"fingerprint" text,
	"change_type" varchar NOT NULL,
	"previous_value" varchar,
	"new_value" varchar,
	"detected_at" timestamp DEFAULT now(),
	"snapshot_date" date NOT NULL,
	"is_test" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "sponsor_enrichment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sponsor_enrichment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fingerprint" varchar(500) NOT NULL,
	"company_number" varchar(20),
	"nature_of_business" text,
	"registered_address" text,
	"website_url" varchar(500),
	"scraped_at" timestamp DEFAULT now(),
	"scrape_status" varchar(20) DEFAULT 'pending' NOT NULL,
	"last_attempted" timestamp,
	"company_status" varchar(50),
	"company_type" varchar(100),
	"incorporation_date" date,
	"sic_codes" jsonb DEFAULT '[]'::jsonb,
	"last_filed_accounts_date" date,
	"next_conf_stmt_due_date" date,
	"dissolved_at" date,
	"companies_house_source" boolean DEFAULT false,
	"fuzzy_match_score" numeric(4, 3),
	"historical_names_raw" jsonb DEFAULT '[]'::jsonb,
	CONSTRAINT "sponsor_enrichment_fingerprint_unique" UNIQUE("fingerprint")
);
--> statement-breakpoint
CREATE TABLE "sponsor_licence_timeline" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sponsor_licence_timeline_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fingerprint" varchar(500) NOT NULL,
	"recorded_date" date NOT NULL,
	"licence_status" varchar(100) NOT NULL,
	"route" varchar(200),
	"type_rating" varchar(50),
	"organisation_name" varchar(500),
	"source" varchar(50) NOT NULL,
	"scraped_at" timestamp with time zone DEFAULT now(),
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sponsor_list" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sponsor_list_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organisation_name" varchar NOT NULL,
	"organisation_name_normalized" varchar NOT NULL,
	"town_city" varchar,
	"county" varchar,
	"type_rating" varchar,
	"route" varchar,
	"fingerprint" text,
	"snapshot_date" date NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sponsor_staging" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sponsor_staging_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"snapshot_id" text NOT NULL,
	"row_num" integer NOT NULL,
	"organisation_name" text NOT NULL,
	"town_city" text,
	"county" text,
	"type_rating" text,
	"route" text,
	"fingerprint" text NOT NULL,
	"snapshot_date" date NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sponsor_watches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"company_name" text NOT NULL,
	"company_number" text,
	"status" varchar DEFAULT 'pending_activation' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"notified_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "subscription_audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subscription_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"changed_by" varchar,
	"source" varchar NOT NULL,
	"previous_status" varchar NOT NULL,
	"new_status" varchar NOT NULL,
	"reason" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "support_tickets" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "support_tickets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"subject" text NOT NULL,
	"message" text NOT NULL,
	"status" varchar DEFAULT 'open' NOT NULL,
	"admin_reply" text,
	"replied_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "system_settings" (
	"key" varchar PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "trusted_patterns" ADD COLUMN "ai_instructions" text;--> statement-breakpoint
ALTER TABLE "trusted_patterns" ADD COLUMN "last_updated" timestamp DEFAULT now();--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "username" varchar;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "hashed_password" varchar;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "credits" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "verification_limit" integer;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "total_verifications_used" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "is_restricted" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "restriction_reason" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "cos_check_approved" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "cos_check_subscription" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "ip_exempt" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "cos_beta_enabled" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "cos_beta_limit" integer;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "deleted_at" timestamp;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "notif_prefs" jsonb;--> statement-breakpoint
ALTER TABLE "verification_results" ADD COLUMN "receipt_id" varchar;--> statement-breakpoint
ALTER TABLE "verification_results" ADD COLUMN "document_hash" varchar;--> statement-breakpoint
ALTER TABLE "verification_results" ADD COLUMN "admin_status" varchar DEFAULT 'pending';--> statement-breakpoint
ALTER TABLE "verification_results" ADD COLUMN "admin_feedback" text;--> statement-breakpoint
ALTER TABLE "verification_results" ADD COLUMN "admin_reviewed_by" varchar;--> statement-breakpoint
ALTER TABLE "verification_results" ADD COLUMN "admin_reviewed_at" timestamp;--> statement-breakpoint
ALTER TABLE "verification_results" ADD COLUMN "accuracy_score" integer;--> statement-breakpoint
ALTER TABLE "verification_results" ADD COLUMN "deleted_at" timestamp;--> statement-breakpoint
ALTER TABLE "company_watches" ADD CONSTRAINT "company_watches_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expert_requests" ADD CONSTRAINT "expert_requests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "global_ai_rules" ADD CONSTRAINT "global_ai_rules_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "job_trigger_audit" ADD CONSTRAINT "job_trigger_audit_triggered_by_users_id_fk" FOREIGN KEY ("triggered_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notif_engine_log" ADD CONSTRAINT "notif_engine_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notif_engine_log" ADD CONSTRAINT "notif_engine_log_change_id_sponsor_changes_id_fk" FOREIGN KEY ("change_id") REFERENCES "public"."sponsor_changes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notif_log" ADD CONSTRAINT "notif_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notif_log" ADD CONSTRAINT "notif_log_change_id_sponsor_changes_id_fk" FOREIGN KEY ("change_id") REFERENCES "public"."sponsor_changes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_log" ADD CONSTRAINT "notification_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_log" ADD CONSTRAINT "notification_log_change_id_sponsor_changes_id_fk" FOREIGN KEY ("change_id") REFERENCES "public"."sponsor_changes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paid_submissions" ADD CONSTRAINT "paid_submissions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paid_submissions" ADD CONSTRAINT "paid_submissions_assigned_to_users_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "push_subscriptions" ADD CONSTRAINT "push_subscriptions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadow_parity_reports" ADD CONSTRAINT "shadow_parity_reports_shadow_run_id_shadow_run_results_id_fk" FOREIGN KEY ("shadow_run_id") REFERENCES "public"."shadow_run_results"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadow_run_results" ADD CONSTRAINT "shadow_run_results_triggered_by_users_id_fk" FOREIGN KEY ("triggered_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sponsor_watches" ADD CONSTRAINT "sponsor_watches_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subscription_audit_log" ADD CONSTRAINT "subscription_audit_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_tickets" ADD CONSTRAINT "support_tickets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_company_watches_user_id" ON "company_watches" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_company_watches_org_normalized" ON "company_watches" USING btree ("organisation_name_normalized");--> statement-breakpoint
CREATE INDEX "idx_company_watches_fingerprint" ON "company_watches" USING btree ("fingerprint");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_csv_archive_date" ON "csv_archive" USING btree ("snapshot_date");--> statement-breakpoint
CREATE INDEX "idx_diff_results_run_date" ON "diff_results" USING btree ("run_date");--> statement-breakpoint
CREATE INDEX "idx_enrichment_queue_poll" ON "enrichment_queue" USING btree ("status","next_attempt_at");--> statement-breakpoint
CREATE INDEX "idx_enrichment_queue_fingerprint" ON "enrichment_queue" USING btree ("fingerprint");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_enrichment_queue_unique" ON "enrichment_queue" USING btree ("fingerprint","job_type");--> statement-breakpoint
CREATE INDEX "idx_expert_requests_status" ON "expert_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_expert_requests_user_id" ON "expert_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_expert_requests_stripe_session_id" ON "expert_requests" USING btree ("stripe_session_id");--> statement-breakpoint
CREATE INDEX "idx_incident_tickets_job" ON "incident_tickets" USING btree ("job_name");--> statement-breakpoint
CREATE INDEX "idx_incident_tickets_severity" ON "incident_tickets" USING btree ("severity");--> statement-breakpoint
CREATE INDEX "idx_incident_tickets_status" ON "incident_tickets" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_incident_tickets_created" ON "incident_tickets" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_job_prefs_user_id" ON "job_alert_preferences" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_job_prefs_fingerprint" ON "job_alert_preferences" USING btree ("fingerprint");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_job_prefs_unique" ON "job_alert_preferences" USING btree ("user_id","fingerprint");--> statement-breakpoint
CREATE INDEX "idx_jobs_fingerprint" ON "job_listings" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "idx_jobs_first_seen" ON "job_listings" USING btree ("first_seen");--> statement-breakpoint
CREATE INDEX "idx_jobs_active" ON "job_listings" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_job_trigger_audit_job_name" ON "job_trigger_audit" USING btree ("job_name","triggered_at");--> statement-breakpoint
CREATE INDEX "idx_job_trigger_audit_triggered_by" ON "job_trigger_audit" USING btree ("triggered_by","triggered_at");--> statement-breakpoint
CREATE INDEX "idx_job_trigger_audit_idempotency" ON "job_trigger_audit" USING btree ("job_name","idempotency_key");--> statement-breakpoint
CREATE INDEX "idx_job_trigger_audit_status" ON "job_trigger_audit" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_notif_engine_log_user_id" ON "notif_engine_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_notif_engine_log_change_id" ON "notif_engine_log" USING btree ("change_id");--> statement-breakpoint
CREATE INDEX "idx_notif_engine_log_status" ON "notif_engine_log" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_notif_engine_log_deliver_after" ON "notif_engine_log" USING btree ("deliver_after");--> statement-breakpoint
CREATE INDEX "idx_notif_log_user_sent" ON "notif_log" USING btree ("user_id","sent_at");--> statement-breakpoint
CREATE INDEX "idx_notification_log_user_id" ON "notification_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_notification_log_change_id" ON "notification_log" USING btree ("change_id");--> statement-breakpoint
CREATE INDEX "idx_notification_log_status" ON "notification_log" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_notification_log_deliver_after" ON "notification_log" USING btree ("deliver_after");--> statement-breakpoint
CREATE INDEX "idx_paid_submissions_stripe_session_id" ON "paid_submissions" USING btree ("stripe_session_id");--> statement-breakpoint
CREATE INDEX "idx_paid_submissions_review_status" ON "paid_submissions" USING btree ("review_status");--> statement-breakpoint
CREATE INDEX "idx_paid_submissions_email" ON "paid_submissions" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_paid_submissions_user_id" ON "paid_submissions" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_push_subscriptions" ON "push_subscriptions" USING btree ("user_id","endpoint");--> statement-breakpoint
CREATE INDEX "idx_push_subscriptions_user_id" ON "push_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_shadow_parity_reports_job_created" ON "shadow_parity_reports" USING btree ("job_name","created_at");--> statement-breakpoint
CREATE INDEX "idx_shadow_parity_reports_shadow_run" ON "shadow_parity_reports" USING btree ("shadow_run_id");--> statement-breakpoint
CREATE INDEX "idx_shadow_run_results_job_created" ON "shadow_run_results" USING btree ("job_name","created_at");--> statement-breakpoint
CREATE INDEX "idx_shadow_run_results_correlation" ON "shadow_run_results" USING btree ("correlation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_sponsor_canonical_fingerprint" ON "sponsor_canonical" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "idx_sponsor_canonical_status" ON "sponsor_canonical" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_sponsor_canonical_current_name" ON "sponsor_canonical" USING btree ("current_name");--> statement-breakpoint
CREATE INDEX "idx_sponsor_canonical_granted_at" ON "sponsor_canonical" USING btree ("granted_at");--> statement-breakpoint
CREATE INDEX "idx_sc_status_name" ON "sponsor_canonical" USING btree ("status","current_name");--> statement-breakpoint
CREATE INDEX "idx_sc_status_town" ON "sponsor_canonical" USING btree ("status","town_city");--> statement-breakpoint
CREATE INDEX "idx_sc_status_type" ON "sponsor_canonical" USING btree ("status","type_rating");--> statement-breakpoint
CREATE INDEX "idx_sponsor_changes_org_name" ON "sponsor_changes" USING btree ("organisation_name");--> statement-breakpoint
CREATE INDEX "idx_sponsor_changes_fingerprint" ON "sponsor_changes" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "idx_sponsor_changes_snapshot_date" ON "sponsor_changes" USING btree ("snapshot_date");--> statement-breakpoint
CREATE INDEX "idx_sponsor_changes_change_type" ON "sponsor_changes" USING btree ("change_type");--> statement-breakpoint
CREATE INDEX "idx_changes_date_type" ON "sponsor_changes" USING btree ("snapshot_date","change_type");--> statement-breakpoint
CREATE INDEX "idx_changes_fp_detected" ON "sponsor_changes" USING btree ("fingerprint","detected_at");--> statement-breakpoint
CREATE INDEX "idx_enrichment_fingerprint" ON "sponsor_enrichment" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "idx_enrichment_scraped_at" ON "sponsor_enrichment" USING btree ("scraped_at");--> statement-breakpoint
CREATE INDEX "idx_enrichment_status" ON "sponsor_enrichment" USING btree ("scrape_status");--> statement-breakpoint
CREATE INDEX "idx_licence_timeline_fingerprint" ON "sponsor_licence_timeline" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "idx_licence_timeline_date" ON "sponsor_licence_timeline" USING btree ("recorded_date");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_licence_timeline_unique" ON "sponsor_licence_timeline" USING btree ("fingerprint","recorded_date","source");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_sponsor_list_org_snapshot" ON "sponsor_list" USING btree ("organisation_name_normalized","snapshot_date");--> statement-breakpoint
CREATE INDEX "idx_sponsor_list_snapshot_date" ON "sponsor_list" USING btree ("snapshot_date");--> statement-breakpoint
CREATE INDEX "idx_sponsor_list_org_name_normalized" ON "sponsor_list" USING btree ("organisation_name_normalized");--> statement-breakpoint
CREATE INDEX "idx_sponsor_list_fingerprint" ON "sponsor_list" USING btree ("fingerprint");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_sponsor_staging_snapshot_row" ON "sponsor_staging" USING btree ("snapshot_id","row_num");--> statement-breakpoint
CREATE INDEX "idx_sponsor_staging_snapshot_id" ON "sponsor_staging" USING btree ("snapshot_id");--> statement-breakpoint
CREATE INDEX "idx_sponsor_staging_fingerprint" ON "sponsor_staging" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "idx_sponsor_watches_user_id" ON "sponsor_watches" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_sponsor_watches_status" ON "sponsor_watches" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_sponsor_watches_company_name" ON "sponsor_watches" USING btree ("company_name");--> statement-breakpoint
CREATE INDEX "idx_sub_audit_user_id" ON "subscription_audit_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_sub_audit_created" ON "subscription_audit_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_sub_audit_source" ON "subscription_audit_log" USING btree ("source");--> statement-breakpoint
CREATE INDEX "idx_support_tickets_user_id" ON "support_tickets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_support_tickets_status" ON "support_tickets" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_support_tickets_created" ON "support_tickets" USING btree ("created_at");--> statement-breakpoint
ALTER TABLE "verification_results" ADD CONSTRAINT "verification_results_admin_reviewed_by_users_id_fk" FOREIGN KEY ("admin_reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_feedback_verification_id" ON "feedback" USING btree ("verification_id");--> statement-breakpoint
CREATE INDEX "idx_feedback_user_id" ON "feedback" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_tp_status" ON "trusted_patterns" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_users_stripe_customer_id" ON "users" USING btree ("stripe_customer_id");--> statement-breakpoint
CREATE INDEX "idx_users_role" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "idx_verification_verified_at" ON "verification_results" USING btree ("verified_at");--> statement-breakpoint
CREATE INDEX "idx_verification_result" ON "verification_results" USING btree ("result");--> statement-breakpoint
CREATE INDEX "idx_verification_user_id" ON "verification_results" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_verification_result_date" ON "verification_results" USING btree ("result","verified_at");--> statement-breakpoint
CREATE INDEX "idx_verification_admin_status" ON "verification_results" USING btree ("admin_status");--> statement-breakpoint
CREATE INDEX "idx_verification_user_verified" ON "verification_results" USING btree ("user_id","verified_at");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_username_unique" UNIQUE("username");--> statement-breakpoint
ALTER TABLE "verification_results" ADD CONSTRAINT "verification_results_receipt_id_unique" UNIQUE("receipt_id");