CREATE TABLE "verification_audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "verification_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"verification_id" integer NOT NULL,
	"actor_id" varchar NOT NULL,
	"action" varchar NOT NULL,
	"previous_admin_status" varchar,
	"new_admin_status" varchar,
	"previous_deleted_at" timestamp,
	"new_deleted_at" timestamp,
	"reason" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "verification_audit_log" ADD CONSTRAINT "verification_audit_log_verification_id_verification_results_id_fk" FOREIGN KEY ("verification_id") REFERENCES "public"."verification_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "verification_audit_log" ADD CONSTRAINT "verification_audit_log_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_verif_audit_verification_id" ON "verification_audit_log" USING btree ("verification_id");--> statement-breakpoint
CREATE INDEX "idx_verif_audit_actor_id" ON "verification_audit_log" USING btree ("actor_id");--> statement-breakpoint
CREATE INDEX "idx_verif_audit_created" ON "verification_audit_log" USING btree ("created_at");