/**
 * Fixtures modelling real UK Home Office Certificate of Sponsorship PDFs.
 *
 * Genuine CoS files are generated by Apache FOP, which writes Dublin Core
 * properties using the RDF container types mandated by the DC spec:
 *   dc:date     -> rdf:Seq
 *   dc:language -> rdf:Bag
 *   dc:format   -> plain text node
 */

/** XMP packet as Apache FOP actually emits it — DC values inside RDF containers. */
export const FOP_XMP_WITH_CONTAINERS = `<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
   <dc:date><rdf:Seq><rdf:li>2026-08-10T10:15:00Z</rdf:li></rdf:Seq></dc:date>
   <dc:format>application/pdf</dc:format>
   <dc:language><rdf:Bag><rdf:li>en-GB</rdf:li></rdf:Bag></dc:language>
  </rdf:Description>
  <rdf:Description rdf:about="" xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
   <pdf:PDFVersion>1.4</pdf:PDFVersion>
   <pdf:Producer>Apache FOP Version 2.9</pdf:Producer>
  </rdf:Description>
  <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
   <xmp:CreateDate>2026-08-10T10:15:00Z</xmp:CreateDate>
   <xmp:CreatorTool>Apache FOP Version 2.9</xmp:CreatorTool>
   <xmp:MetadataDate>2026-08-10T10:15:00Z</xmp:MetadataDate>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>`;

/** Same packet with DC values as bare text nodes (some FOP configurations). */
export const FOP_XMP_PLAIN = FOP_XMP_WITH_CONTAINERS
  .replace('<dc:date><rdf:Seq><rdf:li>2026-08-10T10:15:00Z</rdf:li></rdf:Seq></dc:date>',
           '<dc:date>2026-08-10T10:15:00Z</dc:date>')
  .replace('<dc:language><rdf:Bag><rdf:li>en-GB</rdf:li></rdf:Bag></dc:language>',
           '<dc:language>en-GB</dc:language>');

const INFO_DICT = `1 0 obj\n<< /Producer (Apache FOP Version 2.9) /Creator (Apache FOP Version 2.9) ` +
  `/CreationDate (D:20260810101500Z) /ModDate (D:20260810101500Z) /Title (Certificate of Sponsorship) >>\nendobj`;

/** A single-revision PDF: exactly one startxref. */
export const genuinePdfBinary = (xmp: string = FOP_XMP_WITH_CONTAINERS): string =>
  `%PDF-1.4\n${INFO_DICT}\n${xmp}\ntrailer\n<< /Root 2 0 R >>\nstartxref\n84100\n%%EOF\n`;

/**
 * A LINEARIZED ("fast web view") PDF. Two startxref tokens is the correct,
 * standard structure — the first-page xref plus the main one. Not a re-save.
 */
export const linearizedPdfBinary = (xmp: string = FOP_XMP_WITH_CONTAINERS): string =>
  `%PDF-1.4\n<< /Linearized 1 /L 84210 /O 4 /E 12000 /N 2 /T 84000 >>\n` +
  `startxref\n0\n%%EOF\n${INFO_DICT}\n${xmp}\ntrailer\n<< /Root 2 0 R >>\nstartxref\n84100\n%%EOF\n`;

/** A genuinely re-saved PDF: a true incremental update appended after %%EOF. */
export const incrementallyUpdatedPdfBinary = (): string =>
  `${genuinePdfBinary()}5 0 obj\n<< /Changed true >>\nendobj\ntrailer\n<< /Prev 84100 >>\nstartxref\n90500\n%%EOF\n`;
