import type { PDFMetadata } from './pdfAnalyzer';
import type { COSCheckResult, COSCheck, COSForensic } from '../../shared/mis-types';

const REQUIRED_XMP_FIELDS = [
  'dc:date',
  'dc:format',
  'dc:language',
  'pdf:PDFVersion',
  'pdf:Producer',
  'xmp:CreateDate',
  'xmp:CreatorTool',
  'xmp:MetadataDate',
] as const;

const EDITING_TOOLS: Array<{ pattern: RegExp; name: string }> = [
  { pattern: /ilovepdf/i,         name: 'iLovePDF' },
  { pattern: /smallpdf/i,         name: 'Smallpdf' },
  { pattern: /pdf24/i,            name: 'PDF24' },
  { pattern: /pdfcreator/i,       name: 'PDFCreator' },
  { pattern: /nitro/i,            name: 'Nitro PDF' },
  { pattern: /foxit/i,            name: 'Foxit PDF' },
  { pattern: /pdfescape/i,        name: 'PDFescape' },
  { pattern: /sejda/i,            name: 'Sejda PDF' },
  { pattern: /pdf\.io/i,          name: 'PDF.io' },          // codeql[js/regex/missing-regexp-anchor] - Intentionally unanchored: checks if the string *contains* the tool signature, not whether the full string matches.
  { pattern: /pdfcandy/i,         name: 'PDF Candy' },
  { pattern: /lightpdf/i,         name: 'LightPDF' },
  { pattern: /pdfsam/i,           name: 'PDFsam' },
  { pattern: /photoshop/i,        name: 'Photoshop' },
  { pattern: /illustrator/i,      name: 'Illustrator' },
  { pattern: /gimp/i,             name: 'GIMP' },
  { pattern: /inkscape/i,         name: 'Inkscape' },
  { pattern: /canva/i,            name: 'Canva' },
  { pattern: /microsoft.*word/i,  name: 'Microsoft Word' },
  { pattern: /libreoffice/i,      name: 'LibreOffice' },
  { pattern: /openoffice/i,       name: 'OpenOffice' },
  { pattern: /google docs/i,      name: 'Google Docs' },
  { pattern: /preview/i,          name: 'Apple Preview' },
  { pattern: /pdfium/i,           name: 'PDFium' },
];

export class COSAuthenticityChecker {
  // Accepts the raw PDF binary string (passed from the route — avoids a second file read).
  check(pdfBinary: string, metadata: PDFMetadata): COSCheckResult {
    const checks: COSCheck[] = [];
    let firstFailReason: string | null = null;

    const setEdited = (reason: string) => {
      if (firstFailReason === null) firstFailReason = reason;
    };

    // parsedXmp holds only real values extracted from the XMP block.
    // xmp_tags is synthesised with fallbacks and must NOT be used for presence checks.
    const parsedXmp: Record<string, string> = metadata.parsedXmp ?? {};
    const hasRealXmp = !!metadata.rawXmpData;

    // ── Check 1: Producer must be Apache FOP ─────────────────────────────────
    const producerCheck = this.checkApacheFop(metadata, parsedXmp);
    checks.push(producerCheck);
    if (!producerCheck.passed) setEdited(`not generated by the expected system (Apache FOP)`);

    // ── Check 2: All 8 XMP fields must be present (real values, no fallbacks) ─
    const xmpPresenceCheck = this.checkXmpFieldsPresent(parsedXmp, hasRealXmp);
    checks.push(xmpPresenceCheck);
    if (!xmpPresenceCheck.passed) {
      const missingList = xmpPresenceCheck.detail.replace('Missing: ', '');
      setEdited(`missing ${missingList}`);
    }

    // ── Check 3: XMP fields must be in the correct order ─────────────────────
    if (hasRealXmp) {
      const orderCheck = this.checkXmpFieldOrder(metadata.rawXmpData!);
      checks.push(orderCheck);
      if (!orderCheck.passed) setEdited('XMP fields in unexpected order');
    }

    // ── Check 4: Info dict must match XMP values (only when real XMP exists) ──
    const consistencyCheck = this.checkInfoXmpConsistency(metadata, parsedXmp, hasRealXmp);
    checks.push(consistencyCheck);
    if (!consistencyCheck.passed) setEdited('document properties inconsistent');

    // ── Check 5: No incremental updates — count startxref in the PDF binary ───
    const startxrefMatches = pdfBinary.match(/startxref/g);
    const incrementalCount = Math.max(0, (startxrefMatches ? startxrefMatches.length : 0) - 1);
    const incrementalCheck: COSCheck = {
      name: 'Incremental Updates',
      passed: incrementalCount <= 0,
      detail: incrementalCount <= 0
        ? 'No re-saves detected'
        : `${incrementalCount} re-save(s) detected`,
    };
    checks.push(incrementalCheck);
    if (!incrementalCheck.passed) setEdited('re-saved after initial creation');

    // ── Check 6: No editing tool fingerprints ─────────────────────────────────
    const toolCheck = this.checkEditingTools(metadata);
    checks.push(toolCheck);
    if (!toolCheck.passed) setEdited(`modified using ${toolCheck.detail}`);

    // ── Forensic summary ──────────────────────────────────────────────────────
    const infoXmpConsistency: COSForensic['infoXmpConsistency'] =
      !hasRealXmp ? 'XMP_ABSENT' :
      consistencyCheck.passed ? 'MATCH' : 'MISMATCH';

    const forensic: COSForensic = {
      incrementalUpdates: incrementalCount,
      infoXmpConsistency,
      toolFingerprint: metadata.producer ?? 'Unknown',
      suspiciousIndicators: metadata.forensic?.suspiciousIndicators ?? [],
    };

    // Use real parsed XMP values only — null when field is genuinely absent.
    const xmpTags = {
      'dc:date':          parsedXmp['dc:date']          ?? null,
      'dc:format':        parsedXmp['dc:format']        ?? null,
      'dc:language':      parsedXmp['dc:language']      ?? null,
      'pdf:PDFVersion':   parsedXmp['pdf:PDFVersion']   ?? null,
      'pdf:Producer':     parsedXmp['pdf:Producer']     ?? null,
      'xmp:CreateDate':   parsedXmp['xmp:CreateDate']   ?? null,
      'xmp:CreatorTool':  parsedXmp['xmp:CreatorTool']  ?? null,
      'xmp:MetadataDate': parsedXmp['xmp:MetadataDate'] ?? null,
    } as const;

    return {
      verdict: firstFailReason !== null ? 'EDITED' : 'GENUINE',
      reason:  firstFailReason !== null ? `EDITED — ${firstFailReason}` : null,
      checks,
      xmpTags,
      pdfProperties: {
        author:       metadata.author           ?? null,
        title:        metadata.title            ?? null,
        subject:      metadata.subject          ?? null,
        keywords:     null,
        creationDate: metadata.creationDate     ?? null,
        creator:      metadata.creator          ?? null,
        producer:     metadata.producer         ?? null,
        modDate:      metadata.modificationDate ?? null,
      },
      docStats: {
        characters:    metadata.characterCount ?? 0,
        words:         metadata.wordCount      ?? 0,
        pages:         metadata.pages          ?? 0,
        fileSizeBytes: metadata.fileSize       ?? 0,
      },
      forensic,
    };
  }

  private checkApacheFop(metadata: PDFMetadata, parsedXmp: Record<string, string>): COSCheck {
    const producer = metadata.producer ?? '';
    const xmpProducer = parsedXmp['pdf:Producer'] ?? '';
    const isApacheFop = /apache.?fop/i.test(producer) || /apache.?fop/i.test(xmpProducer);
    return {
      name: 'Apache FOP Producer',
      passed: isApacheFop,
      detail: isApacheFop
        ? `Producer: ${producer || xmpProducer}`
        : `Expected Apache FOP, found: ${producer || 'Unknown'}`,
    };
  }

  private checkXmpFieldsPresent(parsedXmp: Record<string, string>, hasRealXmp: boolean): COSCheck {
    if (!hasRealXmp) {
      return {
        name: 'XMP Fields Present',
        passed: false,
        detail: `Missing: ${REQUIRED_XMP_FIELDS.join(', ')} (no XMP block found)`,
      };
    }
    const missing = REQUIRED_XMP_FIELDS.filter(f => !parsedXmp[f]);
    return {
      name: 'XMP Fields Present',
      passed: missing.length === 0,
      detail: missing.length === 0
        ? 'All 8 required XMP fields present'
        : `Missing: ${missing.join(', ')}`,
    };
  }

  private checkXmpFieldOrder(rawXmp: string): COSCheck {
    const positions = REQUIRED_XMP_FIELDS.map(field => rawXmp.indexOf(field));
    const found = positions.filter(p => p !== -1);
    const isOrdered = found.every((p, i) => i === 0 || p > found[i - 1]);
    return {
      name: 'XMP Field Order',
      passed: isOrdered || found.length < 2,
      detail: isOrdered ? 'XMP fields in expected order' : 'XMP fields out of expected order',
    };
  }

  private checkInfoXmpConsistency(
    metadata: PDFMetadata,
    parsedXmp: Record<string, string>,
    hasRealXmp: boolean,
  ): COSCheck {
    if (!hasRealXmp) {
      return {
        name: 'Info/XMP Consistency',
        passed: false,
        detail: 'No XMP block to compare against Info dictionary',
      };
    }

    const mismatches: string[] = [];

    if (metadata.producer && parsedXmp['pdf:Producer']) {
      if (metadata.producer.trim().toLowerCase() !== parsedXmp['pdf:Producer'].trim().toLowerCase()) {
        mismatches.push('Producer');
      }
    }

    if (metadata.creator && parsedXmp['xmp:CreatorTool']) {
      if (metadata.creator.trim().toLowerCase() !== parsedXmp['xmp:CreatorTool'].trim().toLowerCase()) {
        mismatches.push('CreatorTool');
      }
    }

    if (metadata.creationDate && parsedXmp['xmp:CreateDate']) {
      const infoDate = this.normalizeDate(metadata.creationDate);
      const xmpDate  = this.normalizeDate(parsedXmp['xmp:CreateDate']);
      if (infoDate && xmpDate && infoDate !== xmpDate) {
        mismatches.push('CreateDate');
      }
    }

    return {
      name: 'Info/XMP Consistency',
      passed: mismatches.length === 0,
      detail: mismatches.length === 0
        ? 'Info dictionary matches XMP block'
        : `Mismatch in: ${mismatches.join(', ')}`,
    };
  }

  private checkEditingTools(metadata: PDFMetadata): COSCheck {
    const combined = `${metadata.producer ?? ''} ${metadata.creator ?? ''}`;
    for (const { pattern, name } of EDITING_TOOLS) {
      if (pattern.test(combined)) {
        return { name: 'Editing Tools', passed: false, detail: name };
      }
    }
    return { name: 'Editing Tools', passed: true, detail: 'No editing tools detected' };
  }

  private normalizeDate(dateStr: string): string | null {
    const pdfMatch = dateStr.match(/D:(\d{4})(\d{2})(\d{2})/);
    if (pdfMatch) return `${pdfMatch[1]}-${pdfMatch[2]}-${pdfMatch[3]}`;
    const isoMatch = dateStr.match(/(\d{4})-(\d{2})-(\d{2})/);
    if (isoMatch) return `${isoMatch[1]}-${isoMatch[2]}-${isoMatch[3]}`;
    return null;
  }
}
